# Generated by Django 4.2.13 on 2024-06-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Job Location')),
                ('job_type', models.CharField(
                    choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('IN', 'Internship'),
                             ('FL', 'Freelance')], default='FT', max_length=2, verbose_name='Job Type')),
                ('description', models.TextField(verbose_name='Job Description')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
