# Generated by Django 4.2.13 on 2024-06-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Job Active'),
        ),
    ]
